-- View Columns
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'DimEmployee';


-- Top 10
SELECT TOP 10 * FROM dbo.DimEmployee;

-- Total Rows
SELECT COUNT(*) AS TotalRows FROM dbo.DimEmployee;